services:

    composer:
        image: composer:latest
        volumes:
            - ../../:/usr/local/formflow
        working_dir: /usr/local/formflow
        user: ${MY_UID}:${MY_GID}
        profiles:
            - manual # Will not start with `docker compose up`. Must always be explicitly run with docker compose run composer
        restart: no

    wordpress:
        image: wordpress:latest
        volumes:
            - ../../:/var/www/html/wp-content/plugins/formflow
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wp_user
            WORDPRESS_DB_PASSWORD: wp_pass
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1

            # Local dev environment
            WORDPRESS_CONFIG_EXTRA: |

                /* development parameters */
                define('WP_CACHE', false);
                define('ENVIRONMENT', 'local');

                /* do not re-define WP_DEBUG here or it will throw a blank error in the admin */
                /* you can remove this entirely, this is just to show you what not to do */
                // define('WP_DEBUG', true);
                define( 'WP_DEBUG_DISPLAY', true );

                if (!defined('WP_HOME')) {
                /* force our home url */
                    define('WP_HOME', 'http://localhost');
                    define('WP_SITEURL', WP_HOME);
                }
        restart: no
        networks:
            - formflow_dev

    db:
        image: mariadb:latest
        volumes:
            - ./:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wp_user
            MYSQL_PASSWORD: wp_pass
            MYSQL_ROOT_PASSWORD: root
        command: '--default-authentication-plugin=mysql_native_password'
        restart: no
        networks:
            - formflow_dev

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            PMA_USER: wp_user
            PMA_PASSWORD: wp_pass
            UPLOAD_LIMIT: 512M
        restart: no
        networks:
            - formflow_dev

networks:
    formflow_dev:
        driver: bridge
